// stage-texts.js — сгенерировано build/gen-stage-texts.js.
// Источник текстов: build/kb/countertexts.js (вручную написанные объяснения).
// window.STAGE_PAIR_TEXTS["контрящий__контримый"] = объяснение
// для кнопки «Почему?» на конкретном контр-пике.
window.STAGE_PAIR_TEXTS = {
 "ancient_apparition__abaddon": "Ice Blast запрещает лечение, и Borrowed Time не спасает — Abaddon умирает под фокусом.",
 "doom_bringer__abaddon": "Doom выключает Aphotic Shield и активные спасения, а Break гасит пассивки.",
 "viper__abaddon": "Яды жгут HP, а Viper Strike с Break ломает реген Borrowed Time.",
 "silencer__abaddon": "Global Silence гасит Aphotic Shield и Borrowed Time — Abaddon не может спасти союзника.",
 "huskar__abaddon": "Berserker's Blood даёт реген, который Abaddon не может перебить, а Inner Fire сбивает касты.",
 "shadow_demon__abaddon": "Demonic Purge снимает Aphotic Shield и ломает лечение.",
 "nyx_assassin__abaddon": "Spiked Carapace станит за каст Aphotic Shield, Mana Burn выжигает ману на спасения.",
 "drow_ranger__abyssal_underlord": "Frost Arrows держат Underlord на дистанции, где его Firestorm и Pit бесполезны.",
 "sniper__abyssal_underlord": "Sniper расстреливает Underlord с дистанции больше радиуса Pit и Firestorm.",
 "windrunner__abyssal_underlord": "Windrun уворачивается от Firestorm и Pit, Focus Fire сжигает его с дистанции.",
 "luna__abyssal_underlord": "Eclipse сносит Underlord до того, как он развернёт Firestorm.",
 "slark__abyssal_underlord": "Pounce и Essence Shift крадут силу, Dark Pact снимает Pit.",
 "clinkz__abyssal_underlord": "Searing Arrows жгут с дистанции, Wind Walk уворачивается.",
 "weaver__abyssal_underlord": "Shukuchi уворачивается от Firestorm, Time Lapse откатывает урон.",
 "ancient_apparition__alchemist": "Ice Blast запрещает реген Chemical Rage — Alchemist сгорает после бурста.",
 "antimage__alchemist": "Mana Break выжигает ману, Mana Void наказывает за каждый каст.",
 "nyx_assassin__alchemist": "Mana Burn жжёт ману, Carapace станит за касты.",
 "luna__alchemist": "Eclipse сносит Alchemist до того, как он разгонит Chemical Rage.",
 "tinker__alchemist": "March of Machines давит Alch на дистанции, Hex не даёт кастовать.",
 "viper__alchemist": "Яды и Viper Strike с Break не дают Alch лечиться в Chemical Rage.",
 "sniper__alchemist": "Sniper расстреливает Alch с дистанции, куда его реген не достаёт.",
 "nyx_assassin__ancient_apparition": "Mana Burn выжигает ману, Carapace станит за каст Ice Blast.",
 "slark__ancient_apparition": "Pounce и Essence Shift добираются до хрупкого AA, Shadow Dance прячет от Ice Blast.",
 "riki__ancient_apparition": "Невидимость и урон из тени не дают AA кастовать.",
 "pudge__ancient_apparition": "Hook вытаскивает хрупкого AA, Dismember держит под фокусом.",
 "storm_spirit__ancient_apparition": "Ball Lightning догоняет и бурстит AA до каста Ice Blast.",
 "antimage__ancient_apparition": "Mana Break и Blink добираются до AA, Mana Void карает.",
 "templar_assassin__ancient_apparition": "Meld-крит сносит хрупкого AA из невидимости.",
 "axe__antimage": "Call заставляет AM драться в ближнем бою, Counter Helix наказывает.",
 "bloodseeker__antimage": "Rupture наказывает за каждый Blink, Blood Rite молчит.",
 "riki__antimage": "Невидимость и Smoke Screen не дают AM блинкаться.",
 "legion_commander__antimage": "Duel прижимает AM и не даёт блинкаться, Moment of Courage отбивает урон.",
 "spirit_breaker__antimage": "Charge пробивает Blink и держит цель, Great Bash станит.",
 "slark__antimage": "Essence Shift крадёт ловкость, Dark Pact снимает магию.",
 "doom_bringer__antimage": "Doom выключает Blink и все активы AM.",
 "slark__arc_warden": "Essence Shift крадёт ловкость, Dark Pact снимает Flux.",
 "storm_spirit__arc_warden": "Ball Lightning догоняет обе копии, бурстит до ответа.",
 "earthshaker__arc_warden": "Echo Slam бьёт по двум копиям — урон удваивается.",
 "pudge__arc_warden": "Hook вытаскивает копию из-под Tempest, Dismember держит.",
 "antimage__arc_warden": "Mana Break выжигает ману обеих копий, Mana Void карает.",
 "spectre__arc_warden": "Haunt бьёт по обеим копиям, Dispersion отражает урон.",
 "disruptor__arc_warden": "Glimpse возвращает копию, Kinetic Field ловит обеих.",
 "enchantress__axe": "Untouchable режет скорость атаки Axe, Impetus бьёт с дистанции.",
 "drow_ranger__axe": "Frost Arrows держат Axe на дистанции, где Counter Helix не работает.",
 "sniper__axe": "Sniper расстреливает Axe издалека, куда Call не достаёт.",
 "viper__axe": "Яды не дают Axe сбежать, Viper Strike режет его пассивку.",
 "templar_assassin__axe": "Refraction поглощает Counter Helix, Meld-крит сносит.",
 "razor__axe": "Static Link крадёт урон атаки, Eye of the Storm бьёт по толпе.",
 "necrolyte__axe": "Heartstopper плавит Axe за каждый тик, Reaper's Scythe казнит.",
 "silencer__bane": "Global Silence гасит Fiend's Grip и Nightmare.",
 "nyx_assassin__bane": "Carapace станит за каст Grip, Mana Burn выжигает ману.",
 "rubick__bane": "Spell Steal крадёт Fiend's Grip, Telekinesis держит.",
 "pudge__bane": "Hook вытаскивает Bane из-под его контроля, Dismember держит.",
 "shadow_demon__bane": "Disruption снимает Nightmare, Demonic Purge ломает Grip.",
 "storm_spirit__bane": "Ball Lightning догоняет и бурстит Bane до Grip.",
 "warlock__bane": "Upheaval и Golem не дают Bane уйти, Fatal Bonds усиливает урон.",
 "silencer__batrider": "Global Silence гасит Lasso до того, как Bat утащит.",
 "doom_bringer__batrider": "Doom выключает Firefly и Lasso.",
 "nyx_assassin__batrider": "Carapace станит за каст Lasso, Mana Burn жжёт ману.",
 "puck__batrider": "Phase Shift уходит от Lasso, Dream Coil не даёт утащить.",
 "storm_spirit__batrider": "Ball Lightning уворачивается и бурстит хрупкого Bat.",
 "riki__batrider": "Smoke Screen молчит Bat до Lasso, урон из тени убивает.",
 "queenofpain__batrider": "Blink уходит от Lasso, Sonic Wave бурстит.",
 "slark__beastmaster": "Essence Shift крадёт ловкость, Dark Pact снимает Primal Roar.",
 "puck__beastmaster": "Phase Shift уходит от Roar, Dream Coil не даёт кайтать.",
 "doom_bringer__beastmaster": "Doom выключает Beastmaster и его призывов.",
 "silencer__beastmaster": "Global Silence гасит Roar.",
 "sniper__beastmaster": "Sniper расстреливает Beastmaster и его призывов издалека.",
 "drow_ranger__beastmaster": "Frost Arrows держат дистанцию, Marksmanship карает вблизи.",
 "windrunner__beastmaster": "Windrun уворачивается от Roar, Focus Fire сжигает.",
 "skywrath_mage__bloodseeker": "Concussive Shot замедляет, Mystic Flare бурстит до Rupture.",
 "lion__bloodseeker": "Hex и Finger of Death не дают BS кастовать и убивают бурстом.",
 "lina__bloodseeker": "LSA станит, Laguna Blade сносит до того, как BS разгонится.",
 "doom_bringer__bloodseeker": "Doom выключает Rupture и Blood Rite.",
 "sniper__bloodseeker": "Sniper расстреливает с дистанции, куда Rupture не достаёт.",
 "pudge__bloodseeker": "Hook вытаскивает BS из-под его контроля.",
 "queenofpain__bloodseeker": "Blink уходит от Rupture, Sonic Wave бурстит.",
 "slardar__bounty_hunter": "Corrosive Haze раскрывает невидимость, Crush станит.",
 "bloodseeker__bounty_hunter": "Thirst находит BH на низком HP, Rupture ломает уход.",
 "riki__bounty_hunter": "Два невидимых героя — но Riki видит через Smoke и контрит Track.",
 "zuus__bounty_hunter": "Thundergod's Wrath раскрывает и добивает BH.",
 "antimage__bounty_hunter": "Mana Break и Blink добираются до хрупкого BH.",
 "spirit_breaker__bounty_hunter": "Charge пробивает невидимость и держит цель.",
 "pudge__bounty_hunter": "Hook и Dismember держат хрупкого BH.",
 "silencer__brewmaster": "Global Silence гасит Primal Split — три панды не появляются.",
 "rubick__brewmaster": "Spell Steal крадёт Primal Split.",
 "doom_bringer__brewmaster": "Doom выключает Brewmaster до Split.",
 "pudge__brewmaster": "Hook вытаскивает Brew из-под контроля.",
 "antimage__brewmaster": "Mana Void карает Brewmaster за потраченную ману на Split.",
 "storm_spirit__brewmaster": "Ball Lightning догоняет и бурстит до Split.",
 "riki__brewmaster": "Smoke Screen молчит Brew до Split, урон из тени убивает.",
 "legion_commander__bristleback": "Duel прижимает Bristleback лицом — пассивка спины не работает.",
 "slark__bristleback": "Dark Pact снимает Viscous Nasal Goo, Essence Shift крадёт ловкость и перехиливает Quill.",
 "nyx_assassin__bristleback": "Spiked Carapace станит за каждый Quill Spray — его спам становится самоубийством.",
 "necrolyte__bristleback": "Heartstopper плавит BB за пассивку, Reaper's Scythe казнит.",
 "ancient_apparition__bristleback": "Ice Blast запрещает лечение — BB не переживает фокус.",
 "viper__bristleback": "Яды и Viper Strike с Break режут его реген.",
 "antimage__bristleback": "Mana Break выжигает ману на Quill, Mana Void карает.",
 "earthshaker__broodmother": "Echo Slam бьёт по всем паукам — урон огромный.",
 "legion_commander__broodmother": "Duel прижимает Broodmother, пауки не спасают.",
 "axe__broodmother": "Call собирает пауков, Counter Helix убивает их всех.",
 "bristleback__broodmother": "Quill Spray жжёт пауков по области.",
 "doom_bringer__broodmother": "Doom выключает паучий пул и Insatiable Hunger.",
 "shredder__broodmother": "Flamethrower и Chakram жгут пауков, а деревья-паутина легко срезаются.",
 "pudge__broodmother": "Hook вытаскивает Broodmother из паутины.",
 "doom_bringer__centaur": "Doom выключает Double Edge и ульту — Centaur без урона.",
 "sniper__centaur": "Sniper расстреливает Centaur с дистанции, где Return не работает.",
 "viper__centaur": "Яды и Break не дают Centaur танковать.",
 "drow_ranger__centaur": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "necrolyte__centaur": "Heartstopper плавит Centaur, Reaper's Scythe казнит.",
 "slark__centaur": "Essence Shift крадёт силу, Dark Pact снимает Stomp.",
 "tinker__centaur": "March of Machines и Hex не дают Centaur навязать бой.",
 "earthshaker__chaos_knight": "Echo Slam бьёт по всем иллюзиям CK — урон умножается.",
 "sven__chaos_knight": "Storm Hammer и Cleave бьют по иллюзиям, урон Sven выше.",
 "medusa__chaos_knight": "Stone Gaze обращает иллюзии, Split Shot бьёт по всем.",
 "phantom_lancer__chaos_knight": "Больше иллюзий — больше урон по области, CK не может сфокусить одну.",
 "meepo__chaos_knight": "Несколько Meepo разрывают CK и его иллюзии.",
 "axe__chaos_knight": "Call заставляет иллюзии бить Axe, Counter Helix убивает их.",
 "shredder__chaos_knight": "Whirling Death режет атрибуты, Chakram бьёт по области.",
 "pudge__chen": "Hook вытаскивает Chen, Dismember держит его и призывов.",
 "skywrath_mage__chen": "Mystic Flare бурстит хрупкого Chen до Hand of God.",
 "doom_bringer__chen": "Doom выключает Chen и его призывов.",
 "lina__chen": "LSA и Laguna Blade сносят Chen бурстом.",
 "antimage__chen": "Mana Break и Blink добираются до хрупкого Chen.",
 "enigma__chen": "Black Hole держит Chen и его призывов.",
 "shredder__chen": "Flamethrower жжёт призывов Chen по области.",
 "spirit_breaker__clinkz": "Charge пробивает Wind Walk и держит Clinkz.",
 "nyx_assassin__clinkz": "Carapace станит за атаки, Mana Burn жжёт ману.",
 "slardar__clinkz": "Corrosive Haze раскрывает невидимость и режет броню.",
 "bounty_hunter__clinkz": "Track раскрывает Clinkz и даёт скорость на его кровь.",
 "riki__clinkz": "Smoke Screen молчит и не даёт уйти, урон из тени убивает.",
 "disruptor__clinkz": "Glimpse возвращает Clinkz после Wind Walk, Kinetic Field ловит.",
 "zuus__clinkz": "Thundergod's Wrath раскрывает и добивает.",
 "riki__crystal_maiden": "Невидимость и Smoke Screen убивают хрупкую CM.",
 "slark__crystal_maiden": "Essence Shift крадёт ловкость, Pounce ловит CM.",
 "spirit_breaker__crystal_maiden": "Charge пробивает и держит CM, Great Bash станит.",
 "rattletrap__crystal_maiden": "Battery Assault молчит CM, Power Cogs ловят её в клетку.",
 "storm_spirit__crystal_maiden": "Ball Lightning догоняет и бурстит CM до Freezing Field.",
 "queenofpain__crystal_maiden": "Blink и Sonic Wave сносят хрупкую CM.",
 "tusk__crystal_maiden": "Snowball вкатывается и станит, Walrus Punch добивает.",
 "earthshaker__dark_seer": "Vacuum собирает толпу, но Echo Slam бьёт сильнее — DS кормит ES.",
 "silencer__dark_seer": "Global Silence гасит Vacuum и Surge.",
 "rubick__dark_seer": "Spell Steal крадёт Vacuum и Wall of Replica.",
 "slardar__dark_seer": "Corrosive Haze режет броню, Crush держит.",
 "riki__dark_seer": "Smoke Screen молчит DS, урон из тени убивает.",
 "pudge__dark_seer": "Hook вытаскивает DS из-под его толпы.",
 "zuus__dark_seer": "Глобальный урон бьёт по всей толпе DS.",
 "silencer__dark_willow": "Global Silence гасит Terrorize и Shadow Realm.",
 "nyx_assassin__dark_willow": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__dark_willow": "Smoke Screen не даёт кастовать, урон из тени убивает.",
 "pudge__dark_willow": "Hook вытаскивает хрупкую DW из-под ее контроля.",
 "antimage__dark_willow": "Mana Break и Blink добираются до хрупкой DW.",
 "storm_spirit__dark_willow": "Ball Lightning догоняет и бурстит DW.",
 "bounty_hunter__dark_willow": "Track раскрывает DW и даёт скорость.",
 "silencer__dawnbreaker": "Global Silence гасит Solar Guardian и Hammer.",
 "doom_bringer__dawnbreaker": "Doom выключает Dawnbreaker и её ульту.",
 "slark__dawnbreaker": "Essence Shift крадёт силу, Dark Pact снимает Hammer.",
 "antimage__dawnbreaker": "Mana Break выжигает ману на касты.",
 "pudge__dawnbreaker": "Hook вытаскивает Dawnbreaker из боя.",
 "storm_spirit__dawnbreaker": "Ball Lightning догоняет и бурстит.",
 "batrider__dawnbreaker": "Lasso утаскивает Dawnbreaker из драки до её ульты.",
 "silencer__dazzle": "Global Silence гасит Shallow Grave и Weave.",
 "rubick__dazzle": "Spell Steal крадёт Shallow Grave и Weave.",
 "nyx_assassin__dazzle": "Carapace станит за каст Grave, Mana Burn жжёт.",
 "pudge__dazzle": "Hook вытаскивает хрупкого Dazzle.",
 "riki__dazzle": "Smoke Screen молчит, урон из тени убивает Dazzle.",
 "storm_spirit__dazzle": "Ball Lightning догоняет и бурстит до Grave.",
 "antimage__dazzle": "Mana Break и Blink добираются до хрупкого Dazzle.",
 "silencer__death_prophet": "Global Silence гасит Exorcism — без духов DP без урона.",
 "doom_bringer__death_prophet": "Doom выключает Exorcism и Silence.",
 "nyx_assassin__death_prophet": "Carapace станит за каст, Mana Burn жжёт ману.",
 "antimage__death_prophet": "Mana Break выжигает ману, Mana Void карает за Exorcism.",
 "lina__death_prophet": "Laguna Blade сносит хрупкую DP до того, как она развернёт Exorcism.",
 "tinker__death_prophet": "March and Hex не дают DP держать Exorcism в бою.",
 "storm_spirit__death_prophet": "Ball Lightning догоняет и бурстит DP.",
 "slark__disruptor": "Dark Pact снимает Kinetic Field, Essence Shift крадёт ловкость.",
 "queenofpain__disruptor": "Blink уходит от Glimpse, Sonic Wave бурстит.",
 "storm_spirit__disruptor": "Ball Lightning уворачивается и бурстит Disruptor.",
 "riki__disruptor": "Smoke Screen молчит, урон из тени убивает хрупкого Disruptor.",
 "weaver__disruptor": "Time Lapse откатывает урон, Shukuchi уворачивается.",
 "antimage__disruptor": "Mana Break и Blink добираются до Disruptor, Mana Void карает.",
 "puck__disruptor": "Phase Shift уходит от Kinetic Field, Dream Coil ловит.",
 "sniper__doom_bringer": "Sniper расстреливает Doom с дистанции, куда Doom не достаёт.",
 "slark__doom_bringer": "Dark Pact снимает Doom, Essence Shift крадёт силу и перехиливает.",
 "drow_ranger__doom_bringer": "Frost Arrows держат Doom на дистанции, Marksmanship карает.",
 "windrunner__doom_bringer": "Windrun уворачивается от Doom, Focus Fire сжигает его издалека.",
 "antimage__doom_bringer": "Mana Void карает Doom за потраченную ману, Blink уходит от ульты.",
 "lone_druid__doom_bringer": "Медведь и герой — Doom выключает одного, второй продолжает бить.",
 "tinker__doom_bringer": "March and Hex не дают Doom подойти, Tinker издевается с дистанции.",
 "doom_bringer__dragon_knight": "Doom выключает Dragon Tail и ульту — DK без урона.",
 "sniper__dragon_knight": "Sniper расстреливает DK с дистанции, куда его контроль не достаёт.",
 "viper__dragon_knight": "Яды и Break режут его реген и танкование.",
 "slark__dragon_knight": "Essence Shift крадёт силу, Dark Pact снимает Dragon Tail.",
 "phantom_assassin__dragon_knight": "Coup de Grace криты пробивают DK, Blur уворачивается.",
 "medusa__dragon_knight": "Stone Gaze не даёт DK использовать контроль, Split Shot бьёт по нему.",
 "ursa__dragon_knight": "Fury Swipes быстро стакают урон по DK, Rage не даёт станить.",
 "axe__drow_ranger": "Call заставляет Drow бить вблизи, где Marksmanship отключён.",
 "spirit_breaker__drow_ranger": "Charge пробивает дистанцию и держит Drow, Great Bash станит.",
 "phantom_assassin__drow_ranger": "Blur подходит вплотную, Coup de Grace криты сносят Drow.",
 "slark__drow_ranger": "Essence Shift крадёт ловкость, Pounce ловит Drow вблизи.",
 "storm_spirit__drow_ranger": "Ball Lightning догоняет и бурстит хрупкую Drow.",
 "spectre__drow_ranger": "Haunt добирается до Drow из любой точки, Dispersion отражает урон.",
 "clinkz__drow_ranger": "Searing Arrows жгут с дистанции, Strafe перебивает её урон.",
 "silencer__earth_spirit": "Global Silence гасит Rolling Boulder и Geomagnetic Grip.",
 "doom_bringer__earth_spirit": "Doom выключает Earth Spirit — без камней он бесполезен.",
 "nyx_assassin__earth_spirit": "Carapace станит за каст, Mana Burn жжёт ману.",
 "pudge__earth_spirit": "Hook вытаскивает ES из-под его контроля.",
 "antimage__earth_spirit": "Mana Break выжигает ману на камни.",
 "storm_spirit__earth_spirit": "Ball Lightning уворачивается и бурстит ES.",
 "riki__earth_spirit": "Smoke Screen молчит, урон из тени убивает.",
 "silencer__earthshaker": "Global Silence гасит Fissure и Echo Slam.",
 "rubick__earthshaker": "Spell Steal крадёт Echo Slam и Fissure.",
 "nyx_assassin__earthshaker": "Carapace станит за каст, Mana Burn жжёт ману.",
 "life_stealer__earthshaker": "Rage не даёт станить, Feast перехиливает урон.",
 "storm_spirit__earthshaker": "Ball Lightning уворачивается от Echo Slam.",
 "puck__earthshaker": "Phase Shift уходит от Fissure и Echo Slam.",
 "queenofpain__earthshaker": "Blink уходит от контроля, Sonic Wave бурстит.",
 "silencer__elder_titan": "Global Silence гасит Earth Splitter и Spirit.",
 "doom_bringer__elder_titan": "Doom выключает Elder Titan до его ульты.",
 "storm_spirit__elder_titan": "Ball Lightning уворачивается от Splitter и бурстит.",
 "riki__elder_titan": "Smoke Screen молчит, урон из тени убивает.",
 "slark__elder_titan": "Essence Shift крадёт силу, Dark Pact снимает станы.",
 "pudge__elder_titan": "Hook вытаскивает ET из-под его Spirit.",
 "antimage__elder_titan": "Mana Break выжигает ману, Blink уходит от Splitter.",
 "silencer__ember_spirit": "Global Silence гасит Chains и Flame Guard.",
 "doom_bringer__ember_spirit": "Doom выключает Ember Spirit — без Fire Remnant он мёртв.",
 "skywrath_mage__ember_spirit": "Mystic Flare бурстит Ember до его ухода.",
 "nyx_assassin__ember_spirit": "Carapace станит за каст, Mana Burn жжёт ману.",
 "storm_spirit__ember_spirit": "Ball Lightning догоняет Fire Remnant и бурстит.",
 "antimage__ember_spirit": "Mana Void карает Ember за потраченную ману.",
 "pudge__ember_spirit": "Hook вытаскивает Ember из-под его мобильности.",
 "doom_bringer__enchantress": "Doom выключает Impetus и Untouchable.",
 "viper__enchantress": "Яды и Break не дают Enchantress отхиливаться.",
 "nyx_assassin__enchantress": "Carapace станит за атаки, Mana Burn жжёт.",
 "riki__enchantress": "Smoke Screen молчит, урон из тени убивает.",
 "pudge__enchantress": "Hook вытаскивает Enchantress, Dismember держит.",
 "antimage__enchantress": "Mana Break выжигает ману на касты.",
 "storm_spirit__enchantress": "Ball Lightning догоняет и бурстит Enchantress.",
 "silencer__enigma": "Global Silence гасит Black Hole.",
 "rubick__enigma": "Spell Steal крадёт Black Hole.",
 "earthshaker__enigma": "Echo Slam по толпе Enigma, Fissure прерывает каст.",
 "nyx_assassin__enigma": "Carapace станит за каст Black Hole.",
 "pudge__enigma": "Hook вытаскивает Enigma до Black Hole.",
 "storm_spirit__enigma": "Ball Lightning догоняет и бурстит Enigma.",
 "disruptor__enigma": "Kinetic Field ловит, Static Storm прерывает Black Hole.",
 "night_stalker__faceless_void": "Void ночью пробивает Chronosphere, Criping Fear молчит.",
 "legion_commander__faceless_void": "Duel прижимает Void и не даёт ему Time Walk, Moment of Courage отбивает.",
 "meepo__faceless_void": "Несколько Meepo переживают Chronosphere и разрывают Void.",
 "axe__faceless_void": "Call заставляет Void драться, Counter Helix бьёт даже в Chrono.",
 "slark__faceless_void": "Dark Pact снимает Chronosphere, Essence Shift крадёт ловкость.",
 "lion__faceless_void": "Hex и Finger of Death бурстят Void до Chrono.",
 "earthshaker__furion": "Echo Slam бьёт по всем треантам и Sprout-деревьям.",
 "axe__furion": "Call собирает треантов, Counter Helix убивает их.",
 "legion_commander__furion": "Duel прижимает Furion и не даёт телепортироваться.",
 "pudge__furion": "Hook вытаскивает Furion из-под Sprout.",
 "antimage__furion": "Mana Break и Blink добираются до хрупкого Furion.",
 "phantom_assassin__furion": "Blur подходит, Coup de Grace криты сносят Furion.",
 "bounty_hunter__furion": "Track раскрывает Furion и не даёт телепортироваться.",
 "spectre__grimstroke": "Haunt бьёт по обеим связанным целям.",
 "shadow_shaman__grimstroke": "Hex и Shackles не дают Grimstroke кастовать.",
 "sniper__grimstroke": "Sniper расстреливает Grimstroke с дистанции.",
 "clinkz__grimstroke": "Searing Arrows жгут хрупкого Grimstroke с дистанции.",
 "lycan__grimstroke": "Волки давят Grimstroke, у него нет сейва.",
 "riki__gyrocopter": "Smoke Screen молчит, урон из тени убивает.",
 "slark__gyrocopter": "Essence Shift крадёт ловкость, Dark Pact снимает ракеты.",
 "storm_spirit__gyrocopter": "Ball Lightning догоняет и бурстит Gyro.",
 "phantom_assassin__gyrocopter": "Blur подходит, криты сносят Gyro.",
 "spectre__gyrocopter": "Haunt бьёт по Gyro, Dispersion отражает урон.",
 "medusa__gyrocopter": "Stone Gaze не даёт Gyro использовать Call Down.",
 "antimage__gyrocopter": "Mana Break выжигает ману на касты.",
 "nyx_assassin__hoodwink": "Carapace станит за атаки, Mana Burn жжёт ману.",
 "riki__hoodwink": "Smoke Screen молчит, урон из тени убивает.",
 "slark__hoodwink": "Essence Shift крадёт ловкость, Pounce ловит.",
 "pudge__hoodwink": "Hook вытаскивает хрупкую Hoodwink.",
 "antimage__hoodwink": "Mana Break и Blink добираются до Hoodwink.",
 "storm_spirit__hoodwink": "Ball Lightning догоняет и бурстит.",
 "bounty_hunter__hoodwink": "Track раскрывает Hoodwink, Shadow Walk не спасает.",
 "ancient_apparition__huskar": "Ice Blast запрещает реген — Huskar умирает на низком HP.",
 "viper__huskar": "Яды и Break режут его реген, Viper Strike не даёт уйти.",
 "doom_bringer__huskar": "Doom выключает Berserker's Blood и Inner Fire.",
 "batrider__huskar": "Lasso утаскивает Huskar из драки, Napalm жжёт его реген.",
 "necrolyte__huskar": "Heartstopper плавит Huskar на низком HP, Reaper's Scythe казнит.",
 "axe__huskar": "Call заставляет Huskar бить Axe, Counter Helix убивает его на низком HP.",
 "tinker__huskar": "March and Hex не дают Huskar подойти и кастовать.",
 "nyx_assassin__invoker": "Carapace станит за каст, Mana Burn жжёт ману на комбо.",
 "silencer__invoker": "Global Silence гасит комбо и Sunstrike.",
 "doom_bringer__invoker": "Doom выключает Invoker — без кастов он бесполезен.",
 "storm_spirit__invoker": "Ball Lightning догоняет и бурстит Invoker.",
 "antimage__invoker": "Mana Void карает Invoker за потраченную ману.",
 "riki__invoker": "Smoke Screen молчит, урон из тени убивает.",
 "skywrath_mage__invoker": "Mystic Flare бурстит Invoker, Concussive Shot замедляет.",
 "silencer__jakiro": "Global Silence гасит Macropyre и Ice Path.",
 "rubick__jakiro": "Spell Steal крадёт Macropyre и Ice Path.",
 "nyx_assassin__jakiro": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__jakiro": "Smoke Screen молчит, урон из тени убивает.",
 "slark__jakiro": "Dark Pact снимает Ice Path, Essence Shift крадёт ловкость.",
 "pudge__jakiro": "Hook вытаскивает Jakiro из-под его огня.",
 "storm_spirit__jakiro": "Ball Lightning уворачивается и бурстит Jakiro.",
 "axe__juggernaut": "Call заставляет Juggernaut бить Axe, Counter Helix бьёт даже в Blade Fury.",
 "doom_bringer__juggernaut": "Doom выключает Omnislash и Blade Fury.",
 "phantom_assassin__juggernaut": "Blur подходит, криты пробивают Juggernaut.",
 "slark__juggernaut": "Dark Pact снимает Omnislash, Essence Shift крадёт ловкость.",
 "medusa__juggernaut": "Stone Gaze не даёт Juggernaut зайти в Omnislash, Split Shot бьёт по нему.",
 "spectre__juggernaut": "Haunt бьёт по Juggernaut, Dispersion отражает урон.",
 "riki__juggernaut": "Smoke Screen молчит, урон из тени убивает.",
 "nyx_assassin__keeper_of_the_light": "Carapace станит за каст Illuminate, Mana Burn жжёт ману.",
 "slark__keeper_of_the_light": "Dark Pact снимает Illuminate, Essence Shift крадёт ловкость.",
 "riki__keeper_of_the_light": "Smoke Screen молчит, урон из тени убивает.",
 "pudge__keeper_of_the_light": "Hook вытаскивает KOTL из-под его света.",
 "antimage__keeper_of_the_light": "Mana Break и Blink добираются до хрупкого KOTL.",
 "storm_spirit__keeper_of_the_light": "Ball Lightning догоняет и бурстит KOTL.",
 "bounty_hunter__keeper_of_the_light": "Track раскрывает KOTL, Shadow Walk не спасает.",
 "doom_bringer__kez": "Doom выключает Kez — без кастов он мёртв.",
 "silencer__kez": "Global Silence гасит комбо Kez.",
 "nyx_assassin__kez": "Carapace станит за атаки, Mana Burn жжёт.",
 "antimage__kez": "Mana Break выжигает ману, Blink добирается.",
 "pudge__kez": "Hook вытаскивает Kez из-под его комбо.",
 "storm_spirit__kez": "Ball Lightning догоняет и бурстит Kez.",
 "skywrath_mage__kez": "Mystic Flare бурстит Kez, Concussive Shot замедляет.",
 "storm_spirit__kunkka": "Ball Lightning уворачивается от Torrent и Ghostship.",
 "ember_spirit__kunkka": "Fire Remnant уходит от Ghostship, Sleight of Fist бьёт по Kunkka.",
 "slark__kunkka": "Dark Pact снимает Torrent, Essence Shift крадёт силу.",
 "queenofpain__kunkka": "Blink уходит от Ghostship, Sonic Wave бурстит.",
 "phantom_assassin__kunkka": "Blur подходит, криты сносят Kunkka.",
 "riki__kunkka": "Smoke Screen молчит, урон из тени убивает.",
 "bounty_hunter__kunkka": "Track раскрывает Kunkka, Shadow Walk не спасает.",
 "nyx_assassin__largo": "Carapace станит за каст, Mana Burn жжёт.",
 "slark__largo": "Essence Shift крадёт силу, Dark Pact снимает контроль.",
 "riki__largo": "Smoke Screen молчит, урон из тени убивает.",
 "pudge__largo": "Hook вытаскивает Largo, Dismember держит.",
 "antimage__largo": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__largo": "Ball Lightning догоняет и бурстит.",
 "pugna__legion_commander": "Nether Ward сжигает ману на Duel, Decrepify не даёт LC драться в ближнем бою.",
 "skeleton_king__legion_commander": "Reincarnation переживает Duel, Mortal Strike криты пробивают LC.",
 "winter_wyvern__legion_commander": "Cold Embrace спасает цель от Duel, Winter's Curse заставляет LC бить своих.",
 "obsidian_destroyer__legion_commander": "Astral Imprisonment убирает LC из Duel, Sanity's Eclipse бурстит.",
 "drow_ranger__legion_commander": "Frost Arrows держат дистанцию, Marksmanship карает вблизи.",
 "shadow_shaman__legion_commander": "Hex и Shackles не дают LC кастовать Duel, Serpent Wards давят.",
 "dazzle__legion_commander": "Shallow Grave спасает цель от Duel, Weave режет броню LC.",
 "nyx_assassin__leshrac": "Carapace станит за каждый каст, Mana Burn жжёт ману на комбо.",
 "pudge__leshrac": "Hook вытаскивает Leshrac, Dismember держит хрупкого героя.",
 "rubick__leshrac": "Spell Steal крадёт Split Earth и Pulse Nova.",
 "antimage__leshrac": "Mana Break выжигает ману, Mana Void карает за Pulse Nova.",
 "storm_spirit__leshrac": "Ball Lightning уворачивается от Split Earth и бурстит Leshrac.",
 "silencer__leshrac": "Global Silence гасит касты Leshrac, Last Word карает его спам.",
 "tinker__leshrac": "March and Hex не дают Leshrac кастовать, Laser убивает с дистанции.",
 "nyx_assassin__lich": "Carapace станит за каст Chain Frost, Mana Burn жжёт ману.",
 "slark__lich": "Essence Shift крадёт ловкость, Dark Pact снимает Frost Shield.",
 "storm_spirit__lich": "Ball Lightning догоняет и бурстит хрупкого Lich.",
 "riki__lich": "Smoke Screen молчит, урон из тени убивает Lich.",
 "bounty_hunter__lich": "Track раскрывает Lich, Shadow Walk подбирается незаметно.",
 "antimage__lich": "Mana Break выжигает ману, Blink добирается до Lich.",
 "pudge__lich": "Hook вытаскивает Lich, Dismember держит.",
 "doom_bringer__life_stealer": "Doom выключает Rage и Feast — Lifestealer без защиты.",
 "axe__life_stealer": "Call заставляет Lifestealer бить Axe, Counter Helix режет его HP.",
 "legion_commander__life_stealer": "Duel прижимает Lifestealer, Moment of Courage отбивает урон.",
 "drow_ranger__life_stealer": "Frost Arrows держат дистанцию, Marksmanship перебивает его урон.",
 "shadow_demon__life_stealer": "Disruption убирает Lifestealer из боя, Demonic Purge ломает Rage.",
 "batrider__life_stealer": "Lasso утаскивает Lifestealer, Napalm жжёт его HP.",
 "sniper__life_stealer": "Sniper расстреливает Lifestealer с дистанции, куда его ближний бой не достаёт.",
 "storm_spirit__lina": "Ball Lightning догоняет и бурстит хрупкую Lina до Laguna.",
 "nyx_assassin__lina": "Carapace станит за каст, Mana Burn жжёт ману на комбо.",
 "riki__lina": "Smoke Screen молчит, урон из тени убивает Lina.",
 "slark__lina": "Dark Pact снимает LSA, Essence Shift крадёт ловкость.",
 "spirit_breaker__lina": "Charge пробивает и станит Lina, Great Bash держит её.",
 "puck__lina": "Phase Shift уходит от LSA и Laguna, Dream Coil ловит.",
 "queenofpain__lina": "Blink уходит от Laguna, Sonic Wave бурстит Lina.",
 "storm_spirit__lion": "Ball Lightning догоняет и бурстит Lion до Finger.",
 "riki__lion": "Smoke Screen молчит, урон из тени убивает Lion.",
 "slark__lion": "Dark Pact снимает Hex, Essence Shift крадёт ловкость.",
 "nyx_assassin__lion": "Carapace станит за каст, Mana Burn жжёт ману Lion.",
 "spirit_breaker__lion": "Charge пробивает и станит Lion, Great Bash держит.",
 "bounty_hunter__lion": "Track раскрывает Lion, Shadow Walk подбирается.",
 "puck__lion": "Phase Shift уходит от Hex и Finger, Dream Coil ловит.",
 "nyx_assassin__lone_druid": "Carapace станит за атаки медведя, Mana Burn жжёт ману.",
 "slark__lone_druid": "Essence Shift крадёт ловкость, переживает медведя.",
 "riki__lone_druid": "Smoke Screen молчит, урон из тени убивает LD.",
 "antimage__lone_druid": "Mana Break выжигает ману, Blink добирается.",
 "pudge__lone_druid": "Hook вытаскивает LD из-под медведя.",
 "batrider__lone_druid": "Lasso утаскивает LD, Napalm жжёт его.",
 "ember_spirit__lone_druid": "Sleight of Fist и Chains добивают LD, Fire Remnant уходит от медведя.",
 "riki__luna": "Smoke Screen молчит, урон из тени убивает Luna.",
 "slark__luna": "Essence Shift крадёт ловкость, Dark Pact снимает Lucent Beam.",
 "phantom_assassin__luna": "Blur подходит, Coup de Grace криты сносят Luna.",
 "storm_spirit__luna": "Ball Lightning догоняет и бурстит Luna.",
 "spectre__luna": "Haunt бьёт по Luna, Dispersion отражает урон Eclipse.",
 "antimage__luna": "Mana Break выжигает ману на Eclipse, Blink добирается.",
 "spirit_breaker__luna": "Charge пробивает и станит Luna, Great Bash держит.",
 "earthshaker__lycan": "Echo Slam бьёт по всем волкам Lycan — урон огромный.",
 "axe__lycan": "Call собирает волков, Counter Helix убивает их.",
 "legion_commander__lycan": "Duel прижимает Lycan, Moment of Courage отбивает.",
 "sven__lycan": "Cleave и Warcry бьют по волкам, God's Strength перебивает.",
 "medusa__lycan": "Stone Gaze останавливает волков, Split Shot бьёт по всем.",
 "doom_bringer__lycan": "Doom выключает Lycan и его волков.",
 "sniper__lycan": "Sniper расстреливает Lycan и волков с дистанции.",
 "storm_spirit__magnataur": "Ball Lightning уворачивается от Skewer и RP, бурстит Magnus.",
 "puck__magnataur": "Phase Shift уходит от RP, Dream Coil ловит Magnus.",
 "ember_spirit__magnataur": "Fire Remnant уходит от RP, Sleight of Fist бьёт по Magnus.",
 "slark__magnataur": "Dark Pact снимает Skewer, Essence Shift крадёт силу.",
 "doom_bringer__magnataur": "Doom выключает Magnus до RP.",
 "silencer__magnataur": "Global Silence гасит RP.",
 "rubick__magnataur": "Spell Steal крадёт RP и Reverse Polarity.",
 "doom_bringer__marci": "Doom выключает Marci и её ульту.",
 "silencer__marci": "Global Silence гасит комбо Marci.",
 "slark__marci": "Essence Shift крадёт силу, Dark Pact снимает Dispose.",
 "antimage__marci": "Mana Break выжигает ману, Blink добирается.",
 "pudge__marci": "Hook вытаскивает Marci, Dismember держит.",
 "storm_spirit__marci": "Ball Lightning догоняет и бурстит Marci.",
 "batrider__marci": "Lasso утаскивает Marci из драки.",
 "drow_ranger__mars": "Frost Arrows держат дистанцию, Marksmanship карает вблизи.",
 "sniper__mars": "Sniper расстреливает Mars с дистанции, куда Spear не достаёт.",
 "windrunner__mars": "Windrun уворачивается от Spear, Focus Fire сжигает Mars.",
 "medusa__mars": "Stone Gaze не даёт Mars использовать Arena, Split Shot бьёт по нему.",
 "razor__mars": "Static Link крадёт урон атаки, Eye of the Storm бьёт по Mars.",
 "viper__mars": "Яды и Break режут его танкование, Viper Strike не даёт уйти.",
 "slark__mars": "Essence Shift крадёт силу, Dark Pact снимает Spear.",
 "antimage__medusa": "Mana Break выжигает ману — без маны Medusa бесполезна, Mana Void карает.",
 "nyx_assassin__medusa": "Mana Burn жжёт ману, Carapace станит за каст.",
 "doom_bringer__medusa": "Doom выключает Medusa, Break гасит Split Shot.",
 "slark__medusa": "Essence Shift крадёт ловкость, Dark Pact снимает Stone Gaze.",
 "spectre__medusa": "Haunt бьёт по Medusa, Dispersion отражает её урон.",
 "viper__medusa": "Яды и Break режут её, Viper Strike не даёт убежать.",
 "pudge__medusa": "Hook вытаскивает Medusa из боя, Dismember держит.",
 "earthshaker__meepo": "Echo Slam бьёт по всем клонам Meepo — урон умножается.",
 "sven__meepo": "Cleave и God's Strength разрывают всех Meepo.",
 "ember_spirit__meepo": "Sleight of Fist и Chains бьют по всем клонам, Flame Guard жжёт.",
 "jakiro__meepo": "Liquid Fire и Macropyre жгут всех Meepo по области.",
 "batrider__meepo": "Lasso утаскивает одного Meepo, Napalm жжёт всех.",
 "zuus__meepo": "Thundergod's Wrath бьёт по каждому клону — урон огромный.",
 "luna__meepo": "Eclipse бьёт по всем клонам Meepo.",
 "slardar__mirana": "Corrosive Haze раскрывает Mirana и режет броню, Crush станит.",
 "bounty_hunter__mirana": "Track раскрывает Mirana, Shadow Walk подбирается.",
 "riki__mirana": "Smoke Screen молчит, урон из тени убивает Mirana.",
 "bloodseeker__mirana": "Thirst находит Mirana, Rupture ломает Leap.",
 "storm_spirit__mirana": "Ball Lightning догоняет и бурстит Mirana.",
 "nyx_assassin__mirana": "Carapace станит за каст, Mana Burn жжёт ману.",
 "skywrath_mage__mirana": "Concussive Shot замедляет, Mystic Flare бурстит хрупкую Mirana.",
 "axe__monkey_king": "Call заставляет MK бить Axe, Counter Helix наказывает.",
 "doom_bringer__monkey_king": "Doom выключает MK и его ульту.",
 "slardar__monkey_king": "Corrosive Haze раскрывает MK на деревьях, Crush станит.",
 "bounty_hunter__monkey_king": "Track раскрывает MK, Shadow Walk подбирается.",
 "spirit_breaker__monkey_king": "Charge пробивает и станит MK, Great Bash держит.",
 "riki__monkey_king": "Smoke Screen молчит, урон из тени убивает MK.",
 "bristleback__monkey_king": "Quill Spray жжёт MK вблизи, пассивка BB выживает его бурст.",
 "shadow_demon__morphling": "Disruption убирает Morphling и крадёт атрибуты, Demonic Purge ломает его.",
 "bloodseeker__morphling": "Rupture наказывает за Waveform, Blood Rite молчит.",
 "axe__morphling": "Call заставляет Morphling драться, Counter Helix наказывает.",
 "nyx_assassin__morphling": "Carapace станит за каст, Mana Burn жжёт ману.",
 "keeper_of_the_light__morphling": "Illuminate жжёт ману и HP Morphling, Chakra не даёт ему кастовать.",
 "skywrath_mage__morphling": "Mystic Flare бурстит Morphling, Concussive Shot замедляет.",
 "silencer__morphling": "Global Silence гасит Waveform и Morph, Last Word карает.",
 "riki__muerta": "Smoke Screen молчит, урон из тени убивает хрупкую Muerta.",
 "slark__muerta": "Essence Shift крадёт ловкость, Dark Pact снимает The Calling.",
 "nyx_assassin__muerta": "Carapace станит за каст, Mana Burn жжёт ману.",
 "spirit_breaker__muerta": "Charge пробивает и станит Muerta, Great Bash держит.",
 "antimage__muerta": "Mana Break выжигает ману, Mana Void карает.",
 "pudge__muerta": "Hook вытаскивает Muerta, Dismember держит.",
 "storm_spirit__muerta": "Ball Lightning догоняет и бурстит Muerta.",
 "earthshaker__naga_siren": "Echo Slam бьёт по всем иллюзиям Naga.",
 "ember_spirit__naga_siren": "Sleight of Fist и Chains бьют по всем иллюзиям.",
 "sven__naga_siren": "Cleave разрывает иллюзии, God's Strength перебивает.",
 "medusa__naga_siren": "Split Shot бьёт по всем иллюзиям, Stone Gaze не даёт уйти.",
 "tidehunter__naga_siren": "Ravage держит Naga и её иллюзии, Anchor Smash режет.",
 "sand_king__naga_siren": "Epicenter бьёт по всем иллюзиям.",
 "gyrocopter__naga_siren": "Flak Cannon бьёт по всем иллюзиям, Call Down держит.",
 "ancient_apparition__necrolyte": "Ice Blast запрещает лечение — Necrophos не выживает фокус.",
 "grimstroke__necrolyte": "Ink Swell держит Necrophos, Soulbind дублирует урон.",
 "keeper_of_the_light__necrolyte": "Illuminate жжёт Necrophos с дистанции, Chakra не даёт кастовать.",
 "skywrath_mage__necrolyte": "Mystic Flare бурстит Necrophos, Concussive Shot замедляет.",
 "pugna__necrolyte": "Nether Ward сжигает ману на Heartstopper, Decrepify не даёт лечиться.",
 "lina__necrolyte": "Laguna Blade сносит Necrophos бурстом до Scythe.",
 "muerta__necrolyte": "Pierce the Veil делает урон Muerta чистым — Ghost Shroud не спасает, Dead Shot выбивает Necrophos из позиции.",
 "storm_spirit__nevermore": "Ball Lightning догоняет и бурстит SF до Raze.",
 "nyx_assassin__nevermore": "Carapace станит за каст, Mana Burn жжёт ману.",
 "ember_spirit__nevermore": "Fire Remnant уходит от Requiem, Sleight of Fist бьёт по SF.",
 "slark__nevermore": "Dark Pact снимает Raze, Essence Shift крадёт ловкость.",
 "pudge__nevermore": "Hook вытаскивает SF, Dismember держит.",
 "batrider__nevermore": "Lasso утаскивает SF, Napalm жжёт.",
 "doom_bringer__nevermore": "Doom выключает SF и его урон.",
 "slark__night_stalker": "Dark Pact снимает Crippling Fear, Essence Shift крадёт силу.",
 "riki__night_stalker": "Smoke Screen молчит, урон из тени убивает NS.",
 "batrider__night_stalker": "Lasso утаскивает NS из боя.",
 "pudge__night_stalker": "Hook вытаскивает NS, Dismember держит.",
 "medusa__night_stalker": "Stone Gaze не даёт NS атаковать, Split Shot бьёт по нему.",
 "drow_ranger__night_stalker": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "terrorblade__night_stalker": "Sunder переживает бурст NS, Metamorphosis перебивает его.",
 "slardar__nyx_assassin": "Corrosive Haze раскрывает Nyx и режет броню.",
 "bounty_hunter__nyx_assassin": "Track раскрывает Nyx, Shadow Walk подбирается.",
 "bloodseeker__nyx_assassin": "Thirst находит Nyx, Rupture ломает его уход.",
 "viper__nyx_assassin": "Яды не дают Nyx выйти из Vendetta, Viper Strike держит.",
 "zuus__nyx_assassin": "Thundergod's Wrath раскрывает и добивает Nyx.",
 "riki__nyx_assassin": "Smoke Screen молчит, урон из тени убивает Nyx.",
 "pudge__nyx_assassin": "Hook вытаскивает Nyx, Dismember держит.",
 "huskar__obsidian_destroyer": "Berserker's Blood даёт реген, Inner Fire не даёт OD кастовать.",
 "life_stealer__obsidian_destroyer": "Rage не даёт OD станить, Feast перехиливает.",
 "nyx_assassin__obsidian_destroyer": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__obsidian_destroyer": "Smoke Screen молчит, урон из тени убивает OD.",
 "antimage__obsidian_destroyer": "Mana Break выжигает ману, Mana Void карает за Sanity's Eclipse.",
 "spectre__obsidian_destroyer": "Haunt бьёт по OD, Dispersion отражает урон.",
 "storm_spirit__obsidian_destroyer": "Ball Lightning догоняет и бурстит OD.",
 "nyx_assassin__ogre_magi": "Carapace станит за каст, Mana Burn жжёт ману.",
 "rubick__ogre_magi": "Spell Steal крадёт Fireblast и Multi Cast.",
 "silencer__ogre_magi": "Global Silence гасит касты Ogre, Last Word карает.",
 "antimage__ogre_magi": "Mana Break выжигает ману, Blink добирается.",
 "pudge__ogre_magi": "Hook вытаскивает Ogre, Dismember держит.",
 "storm_spirit__ogre_magi": "Ball Lightning догоняет и бурстит Ogre.",
 "riki__ogre_magi": "Smoke Screen молчит, урон из тени убивает.",
 "antimage__omniknight": "Mana Break выжигает ману, Mana Void карает.",
 "doom_bringer__omniknight": "Doom выключает Guardian Angel и Repel.",
 "nyx_assassin__omniknight": "Carapace станит за каст, Mana Burn жжёт ману.",
 "silencer__omniknight": "Global Silence гасит Guardian Angel и Repel.",
 "rubick__omniknight": "Spell Steal крадёт Guardian Angel и Purification.",
 "pudge__omniknight": "Hook вытаскивает Omni, Dismember держит.",
 "shadow_demon__omniknight": "Demonic Purge снимает Guardian Angel, Disruption убирает Omni.",
 "silencer__oracle": "Global Silence гасит False Promise и Fortune's End.",
 "nyx_assassin__oracle": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__oracle": "Smoke Screen молчит, урон из тени убивает Oracle.",
 "pudge__oracle": "Hook вытаскивает Oracle, Dismember держит.",
 "antimage__oracle": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__oracle": "Ball Lightning догоняет и бурстит Oracle.",
 "bounty_hunter__oracle": "Track раскрывает Oracle, Shadow Walk подбирается.",
 "silencer__pangolier": "Global Silence гасит Roll Up и Rolling Thunder.",
 "doom_bringer__pangolier": "Doom выключает Pangolier и его ульту.",
 "nyx_assassin__pangolier": "Carapace станит за каст, Mana Burn жжёт ману.",
 "antimage__pangolier": "Mana Break выжигает ману, Mana Void карает.",
 "pudge__pangolier": "Hook вытаскивает Pangolier, Dismember держит.",
 "storm_spirit__pangolier": "Ball Lightning догоняет и бурстит Pangolier.",
 "batrider__pangolier": "Lasso утаскивает Pangolier из драки.",
 "axe__phantom_assassin": "Call заставляет PA бить Axe, Counter Helix наказывает.",
 "doom_bringer__phantom_assassin": "Doom выключает PA и Blur.",
 "meepo__phantom_assassin": "Несколько Meepo переживают криты и разрывают PA.",
 "monkey_king__phantom_assassin": "Jingu Mastery отхиливает, Boundless Strike держит PA.",
 "slardar__phantom_assassin": "Corrosive Haze раскрывает Blur и режет броню.",
 "bloodseeker__phantom_assassin": "Thirst находит PA на низком HP, Rupture ломает уход.",
 "skywrath_mage__phantom_assassin": "Mystic Flare бурстит PA до того, как она подойдёт.",
 "earthshaker__phantom_lancer": "Echo Slam бьёт по всем иллюзиям PL.",
 "ember_spirit__phantom_lancer": "Sleight of Fist и Chains бьют по всем иллюзиям, Flame Guard жжёт.",
 "sven__phantom_lancer": "Cleave разрывает иллюзии, God's Strength перебивает.",
 "medusa__phantom_lancer": "Split Shot бьёт по всем иллюзиям, Stone Gaze не даёт уйти.",
 "axe__phantom_lancer": "Call собирает иллюзии, Counter Helix убивает их.",
 "bristleback__phantom_lancer": "Quill Spray жжёт все иллюзии, пассивка выживает бурст PL.",
 "sand_king__phantom_lancer": "Epicenter бьёт по всем иллюзиям.",
 "silencer__phoenix": "Global Silence гасит Supernova и Sun Ray.",
 "doom_bringer__phoenix": "Doom выключает Phoenix и Supernova.",
 "nyx_assassin__phoenix": "Carapace станит за каст, Mana Burn жжёт ману.",
 "pudge__phoenix": "Hook вытаскивает Phoenix, Dismember держит.",
 "antimage__phoenix": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__phoenix": "Ball Lightning догоняет и бурстит Phoenix.",
 "riki__phoenix": "Smoke Screen молчит, урон из тени убивает.",
 "drow_ranger__primal_beast": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "slark__primal_beast": "Essence Shift крадёт силу, Dark Pact снимает Trample.",
 "sniper__primal_beast": "Sniper расстреливает Primal Beast с дистанции.",
 "medusa__primal_beast": "Stone Gaze не даёт Primal Beast атаковать, Split Shot бьёт.",
 "viper__primal_beast": "Яды и Break режут его танкование.",
 "batrider__primal_beast": "Lasso утаскивает Primal Beast из драки.",
 "necrolyte__primal_beast": "Heartstopper плавит его, Reaper's Scythe казнит.",
 "doom_bringer__puck": "Doom выключает Puck — без Phase Shift и Coil он мёртв.",
 "silencer__puck": "Global Silence гасит Phase Shift и Dream Coil.",
 "nyx_assassin__puck": "Carapace станит за каст, Mana Burn жжёт ману.",
 "storm_spirit__puck": "Ball Lightning догоняет и бурстит Puck.",
 "queenofpain__puck": "Blink и Sonic Wave сносят хрупкого Puck.",
 "invoker__puck": "Cold Snap держит Puck, EMP жжёт ману на касты.",
 "skywrath_mage__puck": "Mystic Flare бурстит Puck, Concussive Shot замедляет.",
 "nyx_assassin__pudge": "Carapace станит за каст, Mana Burn жжёт ману на Hook.",
 "rubick__pudge": "Spell Steal крадёт Hook и Dismember.",
 "life_stealer__pudge": "Rage не даёт станить, Feast перехиливает.",
 "legion_commander__pudge": "Duel прижимает Pudge, Moment of Courage отбивает.",
 "huskar__pudge": "Berserker's Blood даёт реген, Inner Fire не даёт кастовать.",
 "undying__pudge": "Decay крадёт силу — Pudge без HP, Tombstone давит.",
 "sniper__pudge": "Sniper расстреливает Pudge с дистанции, куда Hook не достаёт.",
 "sniper__pugna": "Sniper расстреливает Pugna с дистанции, куда его урон не достаёт.",
 "drow_ranger__pugna": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "phantom_assassin__pugna": "Blur подходит, криты сносят хрупкого Pugna.",
 "clinkz__pugna": "Searing Arrows жгут Pugna с дистанции, Wind Walk подходит.",
 "tinker__pugna": "March and Hex не дают Pugna кастовать.",
 "nyx_assassin__pugna": "Carapace станит за каст, Mana Burn жжёт ману.",
 "antimage__pugna": "Mana Break выжигает ману, Mana Void карает.",
 "silencer__queenofpain": "Global Silence гасит Blink и Sonic Wave.",
 "nyx_assassin__queenofpain": "Carapace станит за каст, Mana Burn жжёт ману.",
 "doom_bringer__queenofpain": "Doom выключает QoP и её ульту.",
 "skywrath_mage__queenofpain": "Mystic Flare бурстит QoP, Concussive Shot замедляет.",
 "antimage__queenofpain": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__queenofpain": "Ball Lightning догоняет и бурстит QoP.",
 "riki__queenofpain": "Smoke Screen молчит, урон из тени убивает.",
 "storm_spirit__rattletrap": "Ball Lightning уворачивается от Cogs и Hook, бурстит Clock.",
 "queenofpain__rattletrap": "Blink уходит из Cogs, Sonic Wave бурстит.",
 "slark__rattletrap": "Dark Pact снимает Battery Assault, Essence Shift крадёт.",
 "puck__rattletrap": "Phase Shift уходит от Cogs и Hook.",
 "riki__rattletrap": "Smoke Screen молчит, урон из тени убивает.",
 "ember_spirit__rattletrap": "Fire Remnant уходит от Cogs, Sleight of Fist бьёт.",
 "antimage__rattletrap": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__razor": "Ball Lightning догоняет и бурстит Razor до Static Link.",
 "queenofpain__razor": "Blink уходит от Static Link, Sonic Wave бурстит.",
 "ember_spirit__razor": "Fire Remnant уходит от Static Link, Sleight of Fist бьёт.",
 "sniper__razor": "Sniper расстреливает Razor с дистанции, куда Static Link не достаёт.",
 "viper__razor": "Яды не дают Razor пережить трейд, Break режет Eye of the Storm.",
 "doom_bringer__razor": "Doom выключает Razor и его урон.",
 "skywrath_mage__razor": "Mystic Flare бурстит Razor, Concussive Shot замедляет.",
 "slardar__riki": "Corrosive Haze раскрывает Riki и режет броню.",
 "bounty_hunter__riki": "Track раскрывает Riki, Shadow Walk подбирается.",
 "bloodseeker__riki": "Thirst находит Riki, Rupture ломает уход.",
 "doom_bringer__riki": "Doom выключает Riki и Smoke Screen.",
 "zuus__riki": "Thundergod's Wrath раскрывает и добивает Riki.",
 "disruptor__riki": "Glimpse возвращает Riki, Kinetic Field ловит.",
 "spectre__riki": "Haunt бьёт по Riki, Dispersion отражает урон.",
 "nyx_assassin__ringmaster": "Carapace станит за каст, Mana Burn жжёт ману.",
 "slark__ringmaster": "Essence Shift крадёт ловкость, Dark Pact снимает комбо.",
 "riki__ringmaster": "Smoke Screen молчит, урон из тени убивает.",
 "pudge__ringmaster": "Hook вытаскивает Ring Master, Dismember держит.",
 "antimage__ringmaster": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__ringmaster": "Ball Lightning догоняет и бурстит.",
 "bounty_hunter__ringmaster": "Track раскрывает Ring Master, Shadow Walk подбирается.",
 "silencer__rubick": "Global Silence гасит Telekinesis и украденные спеллы.",
 "nyx_assassin__rubick": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__rubick": "Smoke Screen молчит, урон из тени убивает.",
 "pudge__rubick": "Hook вытаскивает Rubick, Dismember держит.",
 "storm_spirit__rubick": "Ball Lightning догоняет и бурстит Rubick.",
 "antimage__rubick": "Mana Break выжигает ману, Blink добирается.",
 "skywrath_mage__rubick": "Mystic Flare бурстит Rubick, Concussive Shot замедляет.",
 "slardar__sand_king": "Corrosive Haze раскрывает SK под землёй и режет броню.",
 "doom_bringer__sand_king": "Doom выключает SK и его ульту.",
 "silencer__sand_king": "Global Silence гасит Sand Storm и Epicenter.",
 "bounty_hunter__sand_king": "Track раскрывает SK, Shadow Walk подбирается.",
 "zuus__sand_king": "Thundergod's Wrath бьёт по SK в Sand Storm.",
 "nyx_assassin__sand_king": "Carapace станит за каст, Mana Burn жжёт ману.",
 "puck__sand_king": "Phase Shift уходит от Epicenter и Burrowstrike.",
 "silencer__shadow_demon": "Global Silence гасит Disruption и Demonic Purge.",
 "nyx_assassin__shadow_demon": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__shadow_demon": "Smoke Screen молчит, урон из тени убивает.",
 "pudge__shadow_demon": "Hook вытаскивает SD, Dismember держит.",
 "antimage__shadow_demon": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__shadow_demon": "Ball Lightning догоняет и бурстит SD.",
 "bounty_hunter__shadow_demon": "Track раскрывает SD, Shadow Walk подбирается.",
 "silencer__shadow_shaman": "Global Silence гасит Hex и Shackles.",
 "rubick__shadow_shaman": "Spell Steal крадёт Hex и Mass Serpent Ward.",
 "nyx_assassin__shadow_shaman": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__shadow_shaman": "Smoke Screen молчит, урон из тени убивает.",
 "slark__shadow_shaman": "Dark Pact снимает Hex и Shackles, Essence Shift крадёт.",
 "storm_spirit__shadow_shaman": "Ball Lightning догоняет и бурстит SS.",
 "pudge__shadow_shaman": "Hook вытаскивает SS, Dismember держит.",
 "doom_bringer__shredder": "Doom выключает Timbersaw и его ульту.",
 "skywrath_mage__shredder": "Mystic Flare бурстит Timbersaw, Concussive Shot замедляет.",
 "nyx_assassin__shredder": "Carapace станит за каст, Mana Burn жжёт ману.",
 "batrider__shredder": "Lasso утаскивает Timbersaw, Napalm жжёт.",
 "viper__shredder": "Яды и Break режут его реген и реактивность.",
 "necrolyte__shredder": "Heartstopper плавит Timbersaw, Reaper's Scythe казнит.",
 "tinker__shredder": "March and Hex не дают Timbersaw кастовать.",
 "huskar__silencer": "Berserker's Blood даёт реген, Inner Fire не даёт кастовать.",
 "riki__silencer": "Smoke Screen молчит, урон из тени убивает Silencer.",
 "naga_siren__silencer": "Mirror Image убирает Silencer из Global Silence, Ensnare держит.",
 "pudge__silencer": "Hook вытаскивает Silencer, Dismember держит.",
 "doom_bringer__silencer": "Doom выключает Silencer и его Global Silence.",
 "skywrath_mage__silencer": "Mystic Flare бурстит Silencer, Concussive Shot замедляет.",
 "lone_druid__silencer": "Медведь и герой — один переживает Global Silence и добивает.",
 "legion_commander__silencer": "Duel прижимает Silencer, Moment of Courage отбивает.",
 "antimage__skeleton_king": "Mana Break выжигает ману — WK не может Reincarnate.",
 "doom_bringer__skeleton_king": "Doom выключает WK и Reincarnation.",
 "nyx_assassin__skeleton_king": "Mana Burn жжёт ману на Reincarnation, Carapace станит.",
 "luna__skeleton_king": "Eclipse сносит WK, его скелеты кормят Luna.",
 "medusa__skeleton_king": "Stone Gaze не даёт WK атаковать, Split Shot бьёт.",
 "ursa__skeleton_king": "Fury Swipes быстро стакают урон, переживает Reincarnation.",
 "terrorblade__skeleton_king": "Metamorphosis перебивает WK, Sunder переживает его бурст.",
 "nyx_assassin__skywrath_mage": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__skywrath_mage": "Smoke Screen молчит, урон из тени убивает хрупкого Sky.",
 "slark__skywrath_mage": "Essence Shift крадёт ловкость, Dark Pact снимает Silence.",
 "storm_spirit__skywrath_mage": "Ball Lightning догоняет и бурстит Sky.",
 "pudge__skywrath_mage": "Hook вытаскивает Sky, Dismember держит.",
 "antimage__skywrath_mage": "Mana Break выжигает ману, Blink добирается.",
 "spirit_breaker__skywrath_mage": "Charge пробивает и станит Sky, Great Bash держит.",
 "drow_ranger__slardar": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "sniper__slardar": "Sniper расстреливает Slardar с дистанции, куда Crush не достаёт.",
 "windrunner__slardar": "Windrun уворачивается от Crush, Focus Fire сжигает.",
 "viper__slardar": "Яды не дают Slardar подойти, Break режет его.",
 "medusa__slardar": "Stone Gaze не даёт Slardar атаковать, Split Shot бьёт.",
 "weaver__slardar": "Shukuchi уворачивается от Crush, Time Lapse откатывает.",
 "bristleback__slardar": "Quill Spray жжёт Slardar, пассивка выживает его бурст.",
 "bloodseeker__slark": "Thirst находит Slark на низком HP, Rupture ломает его уход.",
 "slardar__slark": "Corrosive Haze раскрывает Slark и режет броню.",
 "doom_bringer__slark": "Doom выключает Slark и Dark Pact.",
 "bounty_hunter__slark": "Track раскрывает Slark, Shadow Walk подбирается.",
 "disruptor__slark": "Glimpse возвращает Slark после Pounce, Kinetic Field ловит.",
 "legion_commander__slark": "Duel прижимает Slark и не даёт убежать.",
 "skywrath_mage__slark": "Mystic Flare бурстит Slark, Concussive Shot замедляет.",
 "riki__snapfire": "Smoke Screen молчит, урон из тени убивает.",
 "slark__snapfire": "Essence Shift крадёт ловкость, Dark Pact снимает Mortimer Kisses.",
 "nyx_assassin__snapfire": "Carapace станит за каст, Mana Burn жжёт ману.",
 "pudge__snapfire": "Hook вытаскивает Snapfire, Dismember держит.",
 "antimage__snapfire": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__snapfire": "Ball Lightning догоняет и бурстит Snapfire.",
 "bounty_hunter__snapfire": "Track раскрывает Snapfire, Shadow Walk подбирается.",
 "spirit_breaker__sniper": "Charge пробивает и станит Sniper, Great Bash держит.",
 "riki__sniper": "Smoke Screen молчит, урон из тени убивает Sniper.",
 "phantom_assassin__sniper": "Blur подходит, криты сносят Sniper.",
 "slark__sniper": "Pounce ловит Sniper, Essence Shift крадёт ловкость.",
 "storm_spirit__sniper": "Ball Lightning догоняет и бурстит Sniper.",
 "spectre__sniper": "Haunt бьёт по Sniper, Dispersion отражает его урон.",
 "antimage__sniper": "Mana Break выжигает ману, Blink добирается.",
 "life_stealer__spectre": "Feast перехиливает урон, Rage не даёт Spectre убежать.",
 "sven__spectre": "God's Strength перебивает Spectre, Warcry держит её урон.",
 "slark__spectre": "Essence Shift крадёт ловкость, Dark Pact снимает Haunt.",
 "doom_bringer__spectre": "Doom выключает Spectre и её ульту.",
 "phantom_assassin__spectre": "Blur подходит, криты сносят Spectre до Dispersion.",
 "medusa__spectre": "Stone Gaze не даёт Spectre атаковать, Split Shot бьёт.",
 "terrorblade__spectre": "Metamorphosis перебивает Spectre, Sunder переживает бурст.",
 "lion__spirit_breaker": "Hex и Finger of Death не дают SB кастовать и убивают.",
 "shadow_shaman__spirit_breaker": "Hex и Shackles держат SB, Serpent Wards давят.",
 "bane__spirit_breaker": "Fiend's Grip держит SB, Nightmare не даёт атаковать.",
 "witch_doctor__spirit_breaker": "Paralyzing Cask держит SB, Death Ward сносит.",
 "disruptor__spirit_breaker": "Glimpse возвращает SB после Charge, Kinetic Field ловит.",
 "storm_spirit__spirit_breaker": "Ball Lightning уворачивается от Charge и бурстит SB.",
 "antimage__spirit_breaker": "Mana Break выжигает ману, Blink уходит от Charge.",
 "nyx_assassin__storm_spirit": "Carapace станит за каст, Mana Burn жжёт ману на Ball Lightning.",
 "silencer__storm_spirit": "Global Silence гасит Ball Lightning и комбо.",
 "skywrath_mage__storm_spirit": "Mystic Flare бурстит Storm, Concussive Shot замедляет.",
 "doom_bringer__storm_spirit": "Doom выключает Storm Spirit и его ульту.",
 "antimage__storm_spirit": "Mana Break выжигает ману, Mana Void карает.",
 "spectre__storm_spirit": "Haunt бьёт по Storm, Dispersion отражает его урон.",
 "invoker__storm_spirit": "EMP жжёт ману Storm, Cold Snap держит его.",
 "phantom_lancer__sven": "Иллюзии PL переживают Storm Hammer и разрывают Sven.",
 "doom_bringer__sven": "Doom выключает Sven и God's Strength.",
 "slark__sven": "Essence Shift крадёт силу, Dark Pact снимает Storm Hammer.",
 "medusa__sven": "Stone Gaze не даёт Sven атаковать, Split Shot бьёт.",
 "antimage__sven": "Mana Break выжигает ману, Blink добирается.",
 "drow_ranger__sven": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "storm_spirit__sven": "Ball Lightning догоняет и бурстит Sven.",
 "bounty_hunter__techies": "Track раскрывает мины, Shadow Walk подбирается.",
 "lycan__techies": "Волки и AOE урон раскидывают мины Techies.",
 "beastmaster__techies": "Дикие животные и Hawk раскрывают мины, Roar держит.",
 "slardar__techies": "Corrosive Haze раскрывает мины, Crush станит.",
 "zuus__techies": "Thundergod's Wrath раскрывает мины и добивает Techies.",
 "spectre__techies": "Haunt бьёт по Techies, Dispersion отражает урон.",
 "nyx_assassin__techies": "Carapace станит за каст, Mana Burn жжёт ману.",
 "spectre__templar_assassin": "Haunt бьёт по TA, Dispersion отражает урон.",
 "phantom_lancer__templar_assassin": "Иллюзии расходуют Refraction и разрывают TA.",
 "phoenix__templar_assassin": "Fire Spirits жгут TA, Supernova выживает её бурст.",
 "medusa__templar_assassin": "Stone Gaze не даёт TA атаковать, Split Shot бьёт.",
 "legion_commander__templar_assassin": "Duel прижимает TA, Moment of Courage отбивает.",
 "viper__templar_assassin": "Яды пробивают Refraction, Break режет её.",
 "venomancer__templar_assassin": "Яды не дают TA пережить, Plague Wards давят.",
 "earthshaker__terrorblade": "Echo Slam бьёт по всем иллюзиям TB.",
 "sven__terrorblade": "Cleave разрывает иллюзии, God's Strength перебивает.",
 "medusa__terrorblade": "Split Shot бьёт по всем иллюзиям, Stone Gaze не даёт уйти.",
 "legion_commander__terrorblade": "Duel прижимает TB, Moment of Courage отбивает.",
 "phantom_lancer__terrorblade": "Больше иллюзий — PL переживает Metamorphosis и разрывает TB.",
 "bristleback__terrorblade": "Quill Spray жжёт иллюзии, пассивка выживает бурст.",
 "antimage__terrorblade": "Mana Break выжигает ману, Mana Void карает.",
 "silencer__tidehunter": "Global Silence гасит Ravage.",
 "rubick__tidehunter": "Spell Steal крадёт Ravage и Anchor Smash.",
 "doom_bringer__tidehunter": "Doom выключает Tidehunter до Ravage.",
 "drow_ranger__tidehunter": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "sniper__tidehunter": "Sniper расстреливает Tide с дистанции, куда его контроль не достаёт.",
 "slark__tidehunter": "Essence Shift крадёт силу, Dark Pact снимает Anchor Smash.",
 "terrorblade__tidehunter": "Metamorphosis перебивает Tide, Sunder переживает.",
 "nyx_assassin__tinker": "Carapace станит за каст, Mana Burn жжёт ману на перекаст.",
 "storm_spirit__tinker": "Ball Lightning догоняет и бурстит Tinker.",
 "spectre__tinker": "Haunt бьёт по Tinker, Dispersion отражает урон.",
 "zuus__tinker": "Thundergod's Wrath раскрывает и добивает Tinker.",
 "antimage__tinker": "Mana Break выжигает ману, Blink добирается.",
 "rattletrap__tinker": "Power Cogs ловят Tinker, Battery Assault молчит его.",
 "pudge__tinker": "Hook вытаскивает Tinker из-под его марша.",
 "slark__tiny": "Essence Shift крадёт силу, Dark Pact снимает Avalanche.",
 "storm_spirit__tiny": "Ball Lightning уворачивается от Avalanche и бурстит Tiny.",
 "ember_spirit__tiny": "Fire Remnant уходит от комбо, Sleight of Fist бьёт.",
 "phantom_lancer__tiny": "Иллюзии расходуют Toss и разрывают Tiny.",
 "riki__tiny": "Smoke Screen молчит, урон из тени убивает.",
 "antimage__tiny": "Mana Break выжигает ману, Blink добирается.",
 "queenofpain__tiny": "Blink уходит от комбо, Sonic Wave бурстит.",
 "doom_bringer__treant": "Doom выключает Treant и его ульту.",
 "silencer__treant": "Global Silence гасит Overgrowth и Leech Seed.",
 "nyx_assassin__treant": "Carapace станит за каст, Mana Burn жжёт ману.",
 "antimage__treant": "Mana Break выжигает ману, Blink добирается.",
 "riki__treant": "Smoke Screen молчит, урон из тени убивает.",
 "pudge__treant": "Hook вытаскивает Treant, Dismember держит.",
 "slardar__treant": "Corrosive Haze режет броню, Crush станит.",
 "doom_bringer__troll_warlord": "Doom выключает Troll и его ульту.",
 "axe__troll_warlord": "Call заставляет Troll бить Axe, Counter Helix наказывает.",
 "phantom_assassin__troll_warlord": "Blur подходит, криты сносят Troll.",
 "riki__troll_warlord": "Smoke Screen молчит, урон из тени убивает.",
 "drow_ranger__troll_warlord": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "sniper__troll_warlord": "Sniper расстреливает Troll с дистанции, куда его ближний бой не достаёт.",
 "windrunner__troll_warlord": "Windrun уворачивается от стана, Focus Fire сжигает.",
 "slark__tusk": "Essence Shift крадёт силу, Dark Pact снимает Snowball.",
 "drow_ranger__tusk": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "sniper__tusk": "Sniper расстреливает Tusk с дистанции.",
 "batrider__tusk": "Lasso утаскивает Tusk из драки.",
 "puck__tusk": "Phase Shift уходит от Snowball и Walrus Punch.",
 "pudge__tusk": "Hook вытаскивает Tusk, Dismember держит.",
 "storm_spirit__tusk": "Ball Lightning догоняет и бурстит Tusk.",
 "nyx_assassin__undying": "Carapace станит за каст, Mana Burn жжёт ману.",
 "slark__undying": "Essence Shift крадёт силу, Dark Pact снимает Decay.",
 "ancient_apparition__undying": "Ice Blast запрещает лечение — Undying не выживает фокус.",
 "lina__undying": "Laguna Blade сносит Undying, LSA держит.",
 "luna__undying": "Eclipse сносит Undying и его зомби.",
 "tinker__undying": "March and Hex не дают Undying кастовать.",
 "ember_spirit__undying": "Sleight of Fist и Chains бьют по всем зомби.",
 "storm_spirit__ursa": "Ball Lightning уворачивается от Overpower и бурстит Ursa.",
 "slark__ursa": "Essence Shift крадёт ловкость, Dark Pact снимает Earthshock.",
 "windrunner__ursa": "Windrun уворачивается от атак Ursa, Focus Fire сжигает.",
 "drow_ranger__ursa": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "phoenix__ursa": "Fire Spirits жгут Ursa, Supernova выживает его бурст.",
 "batrider__ursa": "Lasso утаскивает Ursa из боя.",
 "bane__ursa": "Fiend's Grip держит Ursa, Nightmare не даёт атаковать.",
 "riki__vengefulspirit": "Smoke Screen молчит, урон из тени убивает VS.",
 "slark__vengefulspirit": "Essence Shift крадёт ловкость, Dark Pact снимает Nether Swap.",
 "nyx_assassin__vengefulspirit": "Carapace станит за каст, Mana Burn жжёт ману.",
 "spirit_breaker__vengefulspirit": "Charge пробивает и станит VS, Great Bash держит.",
 "storm_spirit__vengefulspirit": "Ball Lightning догоняет и бурстит VS.",
 "queenofpain__vengefulspirit": "Blink и Sonic Wave сносят VS.",
 "bounty_hunter__vengefulspirit": "Track раскрывает VS, Shadow Walk подбирается.",
 "nyx_assassin__venomancer": "Carapace станит за каст, Mana Burn жжёт ману.",
 "slark__venomancer": "Dark Pact снимает яды, Essence Shift крадёт ловкость.",
 "riki__venomancer": "Smoke Screen молчит, урон из тени убивает Veno.",
 "pudge__venomancer": "Hook вытаскивает Veno, Dismember держит.",
 "antimage__venomancer": "Mana Break выжигает ману, Blink добирается.",
 "spirit_breaker__venomancer": "Charge пробивает и станит Veno.",
 "puck__venomancer": "Phase Shift уходит от ядов, Dream Coil ловит.",
 "sniper__viper": "Sniper расстреливает Viper с дистанции, куда его яды не достают.",
 "storm_spirit__viper": "Ball Lightning догоняет и бурстит Viper.",
 "slark__viper": "Dark Pact снимает яды, Essence Shift крадёт ловкость.",
 "doom_bringer__viper": "Doom выключает Viper и его яды.",
 "drow_ranger__viper": "Frost Arrows держат дистанцию, Marksmanship карает.",
 "weaver__viper": "Shukuchi уворачивается от ядов, Time Lapse откатывает.",
 "riki__viper": "Smoke Screen молчит, урон из тени убивает Viper.",
 "axe__visage": "Call собирает грифонов, Counter Helix убивает их.",
 "earthshaker__visage": "Echo Slam бьёт по грифонам Visage.",
 "jakiro__visage": "Liquid Fire и Macropyre жгут грифонов по области.",
 "luna__visage": "Eclipse сносит Visage и его грифонов.",
 "tinker__visage": "March and Hex не дают Visage кастовать.",
 "medusa__visage": "Split Shot бьёт по грифонам, Stone Gaze не даёт уйти.",
 "batrider__visage": "Lasso утаскивает Visage, Napalm жжёт грифонов.",
 "silencer__void_spirit": "Global Silence гасит комбо Void Spirit.",
 "nyx_assassin__void_spirit": "Carapace станит за каст, Mana Burn жжёт ману.",
 "doom_bringer__void_spirit": "Doom выключает Void Spirit и его ульту.",
 "antimage__void_spirit": "Mana Break выжигает ману, Blink добирается.",
 "pudge__void_spirit": "Hook вытаскивает Void Spirit, Dismember держит.",
 "storm_spirit__void_spirit": "Ball Lightning догоняет и бурстит Void Spirit.",
 "skywrath_mage__void_spirit": "Mystic Flare бурстит Void Spirit, Concussive Shot замедляет.",
 "silencer__warlock": "Global Silence гасит Upheaval и Fatal Bonds.",
 "rubick__warlock": "Spell Steal крадёт Fatal Bonds и Chaotic Offering.",
 "nyx_assassin__warlock": "Carapace станит за каст, Mana Burn жжёт ману.",
 "pudge__warlock": "Hook вытаскивает Warlock, Dismember держит.",
 "skywrath_mage__warlock": "Mystic Flare бурстит Warlock, Concussive Shot замедляет.",
 "antimage__warlock": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__warlock": "Ball Lightning догоняет и бурстит Warlock.",
 "bloodseeker__weaver": "Thirst находит Weaver, Rupture ломает Shukuchi.",
 "doom_bringer__weaver": "Doom выключает Weaver и Time Lapse.",
 "slardar__weaver": "Corrosive Haze раскрывает Weaver и режет броню.",
 "bounty_hunter__weaver": "Track раскрывает Weaver, Shadow Walk подбирается.",
 "nyx_assassin__weaver": "Carapace станит за каст, Mana Burn жжёт ману.",
 "riki__weaver": "Smoke Screen молчит, урон из тени убивает Weaver.",
 "antimage__weaver": "Mana Break выжигает ману, Blink добирается.",
 "doom_bringer__windrunner": "Doom выключает Windrun и Focus Fire.",
 "silencer__windrunner": "Global Silence гасит Windrun и Focus Fire.",
 "nyx_assassin__windrunner": "Carapace станит за каст, Mana Burn жжёт ману.",
 "legion_commander__windrunner": "Duel прижимает Windranger, Moment of Courage отбивает.",
 "zuus__windrunner": "Thundergod's Wrath бьёт по WR в Windrun.",
 "storm_spirit__windrunner": "Ball Lightning догоняет и бурстит WR.",
 "sniper__windrunner": "Sniper расстреливает WR с дистанции.",
 "silencer__winter_wyvern": "Global Silence гасит Winter's Curse и Cold Embrace.",
 "rubick__winter_wyvern": "Spell Steal крадёт Winter's Curse.",
 "nyx_assassin__winter_wyvern": "Carapace станит за каст, Mana Burn жжёт ману.",
 "pudge__winter_wyvern": "Hook вытаскивает WW, Dismember держит.",
 "riki__winter_wyvern": "Smoke Screen молчит, урон из тени убивает.",
 "antimage__winter_wyvern": "Mana Break выжигает ману, Blink добирается.",
 "storm_spirit__winter_wyvern": "Ball Lightning догоняет и бурстит WW.",
 "nyx_assassin__wisp": "Carapace станит за каст, Mana Burn жжёт ману.",
 "storm_spirit__wisp": "Ball Lightning догоняет и бурстит хрупкого Io.",
 "slark__wisp": "Essence Shift крадёт ловкость, Dark Pact снимает Tether.",
 "riki__wisp": "Smoke Screen молчит, урон из тени убивает Io.",
 "antimage__wisp": "Mana Break выжигает ману, Blink добирается.",
 "pudge__wisp": "Hook вытаскивает Io, Dismember держит.",
 "spectre__wisp": "Haunt бьёт по Io и его союзнику, Dispersion отражает.",
 "riki__witch_doctor": "Smoke Screen молчит, урон из тени убивает WD.",
 "slark__witch_doctor": "Essence Shift крадёт ловкость, Dark Pact снимает Cask.",
 "nyx_assassin__witch_doctor": "Carapace станит за каст, Mana Burn жжёт ману.",
 "spirit_breaker__witch_doctor": "Charge пробивает и станит WD.",
 "storm_spirit__witch_doctor": "Ball Lightning догоняет и бурстит WD.",
 "antimage__witch_doctor": "Mana Break выжигает ману, Blink добирается.",
 "tinker__witch_doctor": "March and Hex не дают WD кастовать.",
 "nyx_assassin__zuus": "Carapace станит за каст, Mana Burn жжёт ману.",
 "storm_spirit__zuus": "Ball Lightning догоняет и бурстит хрупкого Zeus.",
 "huskar__zuus": "Berserker's Blood даёт реген, Inner Fire не даёт кастовать.",
 "riki__zuus": "Smoke Screen молчит, урон из тени убивает Zeus.",
 "obsidian_destroyer__zuus": "Astral Imprisonment убирает Zeus, Sanity's Eclipse бурстит.",
 "life_stealer__zuus": "Rage не даёт станить, Feast перехиливает.",
 "spectre__zuus": "Haunt бьёт по Zeus, Dispersion отражает его урон.",
 "bounty_hunter__largo": "Track раскрывает Largo, Shadow Walk подбирается."
};
